package com.hasanjahidul.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Attendance record from ZKTeco device.
 * Constructors are generated by Lombok's @Builder, @NoArgsConstructor,
 * and @AllArgsConstructor annotations.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AttendanceRecord {

    /**
     * Serial number of attendance record
     */
    private Long uid;

    /**
     * User ID
     */
    private String userId;

    /**
     * Authentication type/state
     * 0: Password, 1: Fingerprint, 15: Face, etc.
     */
    private Integer state;

    /**
     * Timestamp of attendance
     */
    private LocalDateTime timestamp;

    /**
     * Attendance type
     * 0: Check-in, 1: Check-out, 2: Break-out, 3: Break-in, 4: OT-in, 5: OT-out
     */
    private Integer type;
}
