package com.hasanjahidul.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Device information from ZKTeco device.
 * Constructors are generated by Lombok's @Builder, @NoArgsConstructor,
 * and @AllArgsConstructor annotations.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DeviceInfo {

    /**
     * Device firmware version
     */
    private String version;

    /**
     * Device OS version
     */
    private String osVersion;

    /**
     * Device platform
     */
    private String platform;

    /**
     * Device serial number
     */
    private String serialNumber;

    /**
     * Device name
     */
    private String deviceName;

    /**
     * Device time
     */
    private LocalDateTime deviceTime;

    /**
     * Number of users
     */
    private Integer userCount;

    /**
     * Number of fingerprint templates
     */
    private Integer fingerprintCount;

    /**
     * Number of attendance records
     */
    private Integer attendanceCount;

    /**
     * Face template count
     */
    private Integer faceCount;
}
