package com.hasanjahidul.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * User information from ZKTeco device.
 * Constructors are generated by Lombok's @Builder, @NoArgsConstructor,
 * and @AllArgsConstructor annotations.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserInfo {

    /**
     * User unique ID (UID)
     */
    private Integer uid;

    /**
     * User ID
     */
    private String userId;

    /**
     * User name
     */
    private String name;

    /**
     * Password
     */
    private String password;

    /**
     * Card number
     */
    private Long cardno;

    /**
     * Role/Privilege
     * 0: Common user, 14: Administrator
     */
    private Integer role;

    /**
     * Group ID
     */
    private String groupId;

    /**
     * User timezone
     */
    private String timezone;
}
