package com.hasanjahidul.config;

import com.hasanjahidul.service.ZKTecoDeviceService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Auto-configuration for ZKTeco SDK.
 * Automatically configures ZKTecoDeviceService bean when required properties
 * are present.
 * Constructor is generated by Spring.
 */
@Slf4j
@Configuration
@ConditionalOnClass(ZKTecoDeviceService.class)
@EnableConfigurationProperties(ZKTecoProperties.class)
public class ZKTecoAutoConfiguration {

    /**
     * Creates and configures ZKTecoDeviceService bean
     *
     * @param properties ZKTeco configuration properties
     * @return configured ZKTecoDeviceService instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(name = "zkteco.ip-address")
    public ZKTecoDeviceService zkTecoDeviceService(ZKTecoProperties properties) {
        log.info("Initializing ZKTeco Device Service for IP: {}", properties.getIpAddress());

        ZKTecoDeviceService service = new ZKTecoDeviceService(
                properties.getIpAddress(),
                properties.getPort()
        );

        if (properties.isAutoConnect()) {
            try {
                boolean connected = service.connect();
                if (connected) {
                    log.info("Successfully connected to ZKTeco device");
                } else {
                    log.warn("Failed to connect to ZKTeco device");
                }
            } catch (Exception e) {
                log.error("Error connecting to ZKTeco device: {}", e.getMessage(), e);
            }
        }

        return service;
    }
}
